name: Compile and Release MicroPython firmware

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize Micropython submodule and submodules
      run: |
        git submodule update --init lib/micropython
        cd lib/micropython
        git submodule update --init lib/stm32lib lib/mbedtls lib/lwip lib/micropython-lib

    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabi

    - name: Make MicroPython CC
      run: |
        make -C lib/micropython/mpy-cross
        cd ../../

    - name: Build the HEX files
      run: |
        for board_dir in mcu/*/; do
          cd "$board_dir"
          make -j$(nproc) LTO=1
          board_name=$(basename "$board_dir")
          mkdir -p release
          cp build/firmware.hex "release/${board_name}.hex"
          make clean
        done
        cd ../../

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          mcu/*/release/*.hex
        body: |
          Release created automatically from commit: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
